source ~/.antigen.zsh

antigen use oh-my-zsh

antigen bundle git
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle rimraf/k
antigen bundle kennethreitz/autoenv

antigen apply

source ~/.bash_profile
